backend:
  name: github
  repo: komatic5/gdcs2
  base_url: https://gdcsauth.officialxyno.workers.dev
  auth_endpoint: /auth
  branch: main
  open_authoring: true

media_folder: /static/media
public_folder: /media
publish_mode: editorial_workflow
site_url: https://www.gdcreatorschool.com/

fields: &page_fields
  - { label: Draft, name: draft, widget: boolean,
    hint: "Enabling draft mode lets you save your changes, but doesn't make them available on the website."}
  - { label: Title, name: title, widget: string }
  - { label: Date, name: date, widget: datetime, time_format: false, format: "YYYY-MM-DD" }
  - label: SEO
    name: seo
    widget: object
    collapsed: true
    required: false
    hint: "The SEO (title and description) people will see when viewing your guide online."
    fields:
    - { label: Title, name: title, widget: string, required: false }
    - { label: Description, name: description, widget: text, required: false }
    - { label: Canonical URL, name: canonical, widget: string, required: false }
    - { label: No Index, name: noindex, widget: boolean, required: false }
  - { label: Weight, name: weight, widget: number,
    hint: "Pages with high weight will display below pages with low weight.\nLook at other guides in this folder to see where to place your own." }
  - { label: Math, name: math, widget: boolean, required: false,
    hint: "Lets you use MathJax for math formatting in your guide."}
  - { label: Body, name: body, widget: markdown }

collections:
  - name: editor
    label: The Editor
    label_singular: Guide
    folder: "content/docs/guides/the-editor"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: main-skills
    label: General Skills
    label_singular: Guide
    folder: "content/docs/guides/main-skills"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: tr1
    label: Triggers 1
    label_singular: Guide
    folder: "content/docs/guides/triggers-1"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: gp1
    label: Gameplay 2
    label_singular: Guide
    folder: "content/docs/guides/gameplay-1"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: dc1
    label: Deco 1
    label_singular: Guide
    folder: "content/docs/guides/deco-1"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: tr2
    label: Triggers 2
    label_singular: Guide
    folder: "content/docs/guides/triggers-2"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: gp2
    label: Gameplay 2
    label_singular: Guide
    folder: "content/docs/guides/gameplay-2"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: dc2
    label: Deco 2
    label_singular: Guide
    folder: "content/docs/guides/deco-2"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: tr3
    label: Triggers 3
    label_singular: Guide
    folder: "content/docs/guides/triggers-3"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: dc3
    label: Deco 3
    label_singular: Guide
    folder: "content/docs/guides/deco-3"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    fields: *page_fields
    create: true

  - name: contributing
    label: Contributing
    label_singular: Guide
    folder: "content/contributing"
    slug: "{{slug}}"
    sortable_fields: []
    summary: "[Draft: {{ draft }}] - {{ title }}"
    nested:
      depth: 5
      subfolders: false
    fields: *page_fields
    create: true
